### ISSUE TITLE
 不是有效的 Win32 应用程序。

### ISSUE THREAD

**Issue by BeanKaKa** [LoseNine/Crack-Website-code#3]
文件“C:\Users\asda\AppData\Local\Programs\Python\Python36\lib\ctypes_init _.py”，第 348 行，init self._handle
= _dlopen(self._name, mode)
OSError: [WinError 193 ] %1 不是有效的 Win32 应用程序。

**Comment by BeanKaKa** [comment]
emmm，C:\Users\Administrator\Desktop\Crack-Website-code-master\Crack-Website-code-master>python run.py
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\Crack-Website-code-master\Crack-Website-code-master\run.py", line 1, in <module>
    from core import test
  File "C:\Users\Administrator\Desktop\Crack-Website-code-master\Crack-Website-code-master\core\test.py", line 19
    """
       ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 42-43: truncated \UXXXXXXXX escape

**Comment by pengmude** [comment]
库文件“MCG_DLL.dll”是不是缺少了？项目文件不完整
